[package]
name = "async-bpm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arc-swap = "1.7.1"
arrayref = "0.3.7"
async-channel = "2.2.0"
derivative = "2.2.0"
futures = "0.3.30"
io-uring = { version = "0.6.3", features = ["direct-syscall"] }
libc = "0.2.153"
rand = { version = "0.8.5", features = ["small_rng"] }
send_wrapper = "0.6.0"
thread_local = "1.1.8"
tokio = { version = "1.37.0", features = ["sync", "rt", "net", "macros"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[dev-dependencies]
tokio = { version = "1.37.0", features = ["full"] }
