[package]
name = "async-bpm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-queue = "0.3.11"
io-uring = "0.6.3"
slab = "0.4.9"
tokio = { version = "1.36.0", features = ["sync", "rt", "net"] }
