[package]
name = "async-bpm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-queue = "0.3.11"
io-uring = "0.6.3"
libc = "0.2.153"
send_wrapper = "0.6.0"
thread_local = "1.1.8"
tokio = { version = "1.37.0", features = ["sync", "rt", "net", "macros"] }

[dev-dependencies]
tokio = { version = "1.37.0", features = ["full"] }
