[package]
name = "async-bpm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-channel = "2.3"
libc = "0.2.158"
scc = "2.1"
send_wrapper = "0.6.0"
thread_local = "1.1.8"
tokio = { version = "1.39", features = ["macros", "rt", "sync", "time"] }
tokio-uring = "0.5.0"

[dev-dependencies]
tokio = { version = "1.39", features = ["full"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = true
