[package]
name = "async-bpm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-channel = "2.3"
derivative = "2.2"
rand = "0.8"
send_wrapper = "0.6"
thread_local = "1.1"
tokio = { version = "1.37", features = ["sync"] }
tokio-uring = "0.5"

[dev-dependencies]
tokio = { version = "1.37", features = ["full"] }

[profile.release]
debug = true
